### ISSUE TITLE
error

### ISSUE THREAD

**Issue by DaveLeeBoy** [HopeFE/CTPH_H5_WX#1]
为什么我npm run dev 之后给我报这个错
tag <flexbox> has no matching end tag.
但是我看了文件发现都闭合了标签的，这是怎么回事

**Comment by Kyncc** [comment]
贴下报错的信息吧 我看下 我这边还没有这个报错呢

**Comment by DaveLeeBoy** [comment]
![image](https://cloud.githubusercontent.com/assets/24412146/24037427/bbad55b0-0b38-11e7-95bf-6761a5d7be22.png)

**Comment by Kyncc** [comment]
我提交了你在试试， 我这边没闭合也不抱错。不知道为什么

**Comment by DaveLeeBoy** [comment]
恩，好的！我重新克隆下
